import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  heading: {
    marginTop: 100,
    display: "flex",
    alignItems: "center",
  },
  headingText: {
    fontWeight: "bold",
    fontSize: 25,
  },
  boldHorizontalLine: {
    borderColor: "#F9F9F9",
    opacity: 0.7,
    borderWidth: 0,
    height: 1,
    // marginLeft: 30,
    // marginRight: 30,
    marginTop: 10,
    // marginBottom: 10,
    backgroundColor: "#F3E9E5",
    // borderRadius: 5,
    elevation: 10,
  },
  foodItemsContainer: {
    maxHeight: 400,
  },
  dottedHorizontalLine: {
    borderColor: "#F3E9E5",
    borderStyle: "dotted",
    borderTopWidth: 2,
    height: 5,
    marginLeft: 30,
    marginRight: 30,
    marginTop: 10,
    marginBottom: 10,
  },
  addFoodItemContainer: {
    flexDirection: "row",
    // justifyContent : 'center',
    alignItems: "center",
    borderColor: "#B1E8CE",
    borderWidth: 2,
    borderRadius: 10,
    padding: 10,
    marginLeft: 10,
    marginRight: 10,
    marginTop: 10,
    marginBottom: 10,
    backgroundColor: "#F5F5F5",
  },
  addFoodItemTextStyle: {
    fontWeight: "bold",
    fontSize: 18,
  },
  icons: {
    marginLeft: 10,
    marginRight: 10,
  },
  mediumBoldText: {
    fontWeight: "bold",
    fontSize: 20,
  },
  smallBoldText: {
    fontWeight: "bold",
    fontSize: 15,
  },
  smallText: {
    fontSize: 15,
  },
  finalFoodListContainerButton: {
    borderColor: "#D3D3D3",
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: "#03B660",
    display: "flex",
    alignItems: "center",
  },
  finalFoodListContainerButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20,
  },
});
